// Auto-generated by daily cron — DO NOT edit manually
// Each article is added here after being written and reviewed

export interface BlogArticle {
  slug: string;
  title: string;
  excerpt: string;
  category: string;
  readingTime: string;
  date: string;
  coverImage: string;
  featured: boolean;
  author: string;
  content: string; // HTML content
}

export const articles: BlogArticle[] = [
  // Articles will be added here by the daily cron job
];
