export const MOBILE_SCROLL_OFFSET = -140;
export const ANIMATION_STAGGER_DELAY = 0.05;
export const SPLASH_PROGRESS_INCREMENT = 1.5;
export const SPLASH_COMPLETION_DELAY = 600;
export const SHIFT_UPDATE_INTERVAL = 60000;
export const DESKTOP_BREAKPOINT = 1024;
